const warriorTraits = {
    'Rune of Power': 1.7,
    'Rune of Protection': 1.7,
    'Firebrand': 1.5,
    'Rune of Up': 1.25,
    'Goblin Raider': 1.4,
    'Goblin': 1.4,
    'Capped Goblin': 1.4,
    'Goblin Chieftain': 1.4,
    'Street Punk Goblin': 1.4,
    'Kobold Captain': 2,
    'Wild Kobold': 2,
    'Kobold Grunt': 2,
    'Blood Sword': 1.4,
    'Cardinal Raptor': 2,
    'Obsidian Raptor': 2,
    'Furgnome Mercenary': 1.4,
    'Furgnome Marauder': 1.4,
    'Oni Girl': 1.25,
    'Dominatrix': 1.25,
    'Chad Bro': 1.25,
    'Superalloy Bot': 1.7,
    'Megasuit': 1.25,
    'Dark Ronin Armor': 1.25,
    'Street Punk Kobold': 1.25,
    'Argyropoeia Bot': 1.7,
    'Cyber': 1.7,
    'Metabot': 1.25,
    'Executioner': 1.25,
    'Cyber Marauder': 1.25,
    'Fungus': 1.4,
    'Guardian Helm': 1.25,
    'Hood of Torment': 1.25,
    'Blood Horn Helm': 1.5,
    'BucketHead: Atomic 26': 1.7,
    'Ether Horn Helm': 1.5,
    'Rocket Helm': 1.25,
    'Trident': 1.25,
    'Amaryllis Fey Sword': 1.25,
    'Cat Girl': 1.25,
    'Agapanthus Fey Sword': 1.25,
    'Mug of Ale': 1.25,
    'Flame Thrower': 1.25,
    'Sword of Babylon': 1.25,
    'Silver Dragon Pike': 1.25,
    'Jade Sword': 1.25,
    'Cyber Axe': 1.25,
    'Scarlet Macaw': 1.25,
    'Silver Goat': 1.25,
    'Attack Drone': 1.25,
};

const wizardTraits = [
    'Flaming Skull',
    'Kobold'
]

module.exports = {
    warriorTraits: warriorTraits,
    wizardTraits: wizardTraits
}